In [1]:
import numpy as np

In [4]:
np_abjad = np.array(['a','b','c','d','e'])

In [8]:
np_vokal_konsonan = np.array([['a','e','i','o','u'],['b','c','d','f','g']])

In [9]:
#ndim
np_abjad.ndim

1

In [11]:
#ndim
np_vokal_konsonan.ndim

2

In [12]:
#shape
np_abjad.shape

(5,)

In [13]:
#shape
np_vokal_konsonan.shape

(2, 5)

In [14]:
#size
np_abjad.size

5

In [15]:
#size
np_vokal_konsonan.size

10

In [16]:
#dtype
np_abjad.dtype

dtype('<U1')

In [17]:
np.add(5,8)

13

In [22]:
np.array([1+2+3+4+5])

array([15])

In [23]:
np_angka = np.array([15,22,31,49,50])

In [25]:
#AND
np.logical_and(np_angka>25,np_angka<45)

array([False, False,  True, False, False])

In [26]:
#OR
np.logical_or(np_angka<25,np_angka>45)

array([ True,  True, False,  True,  True])

In [29]:
#NOT
np.logical_not(np_angka==15)

array([False,  True,  True,  True,  True])

In [33]:
#XOR
np.logical_xor(np_angka>20,np_angka<40)

array([ True, False, False,  True,  True])

In [35]:
np_angka[0]

15

In [36]:
np_angka[-1]

50

In [37]:
np_angka[-2]

49

In [38]:
np_angka[0:4]

array([15, 22, 31, 49])

In [39]:
arr_A = np.array([[1,2,3,4,5],[2,4,6,8,10]])

In [41]:
arr_A[1,2]

6

In [42]:
arr_A[:,2]

array([3, 6])

In [44]:
arr_A[1,:]

array([ 2,  4,  6,  8, 10])

In [50]:
NAMA = np.array(['Parjo','Bagus','Aji'])

In [51]:
for sambutan in NAMA:
    print('Halo', sambutan)

Halo Parjo
Halo Bagus
Halo Aji
